name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Retrain model
      run: python retrain.py

    - name: Run tests
      run: |
        pytest tests/

    - name: Build Docker image
      run: docker build -t sarcasm-detector .

    - name: Save Docker image as artifact
      run: docker save sarcasm-detector | gzip > sarcasm-detector.tar.gz

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: sarcasm-image
        path: sarcasm-detector.tar.gz

  deploy:
    runs-on: self-hosted  # assumes your Swarm node is self-hosted runner
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Download Docker image artifact
      uses: actions/download-artifact@v4.3.3
      with:
        name: sarcasm-image

    - name: Load Docker image
      run: gunzip -c sarcasm-detector.tar.gz | docker load

    - name: Deploy to Docker Swarm
      run: docker stack deploy -c swarm-deploy.yml sarcasmstack
