name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Retrain model
      run: python retrain.py

    - name: Run tests
      run: pytest tests/

    - name: Build Docker image
      run: |
        docker build -t sarcasm-detector . || (echo "Docker build failed!" && exit 1)

    - name: Save Docker image as artifact
      run: |
        docker save sarcasm-detector | gzip > sarcasm-detector.tar.gz
        echo "Docker image saved as sarcasm-detector.tar.gz"

    - name: Verify artifact file exists
      run: |
        if [ ! -f sarcasm-detector.tar.gz ]; then
          echo "Artifact file not found!"
          exit 1
        fi

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: sarcasm-image
        path: sarcasm-detector.tar.gz

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: sarcasm-image

    - name: Load Docker image
      run: gunzip -c sarcasm-detector.tar.gz | docker load

    - name: Deploy to Docker Swarm
      run: docker stack deploy -c swarm-deploy.yml sarcasmstack
