name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Retrain model
      run: python retrain.py

    - name: Run tests
      run: |
        pytest tests/

    - name: Build Docker image
      run: docker build -t sarcasm-detector .

    - name: Push to Docker Hub (optional)
      run: echo "Push step here"

    - name: Deploy to Kubernetes
      run: echo "kubectl apply -f k8s/deployment.yaml"
